#!/bin/bash

display_help_for_aku(){
	awk 'BEGIN {
		print "### awk util"
		print ""
		print "[SUB_CMD]"
		print "## awk"
		print "\ttSet gnu awk path"
		print "\tType aku awk -h for more help "
		print ""
		print "## trm"
		print "\ttrm space or etc"
		print "\tType aku trim -h for more help "
		print ""
		print "## cut"
		print "\ttcut field"
		print "\tType aku cut -h for more help "
		print ""
		print "## rep"
		print "\ttrepi by field"
		print "\tType aku rep -h for more help "
		print ""
		print "## mch"
		print "\ttmatch by  field"
		print "\tType aku mch -h for more help "
		print ""
		print "## hld"
		print "\ttEctract str bitween start and end holder by or"
		print "\tType aku hld -h for more help "
		print ""
		print "## c2s"
		print "\ttConvert cammel case to snake"
		print "\tType aku c2s -h for more help "
	}' | less
}
