#!/bin/bash

set -eu


LANG=C
AKU_SUB_CMD="${1:-}"
readonly AKU_CMD_NAME="$(basename $0)"
readonly AKU_LIBS_DIR_PATH="$(cd $(dirname $0) ; pwd)"
readonly EXEC_FILE_DIR="${AKU_LIBS_DIR_PATH}/aku_libs"
readonly HELP_DIR_PATH="${EXEC_FILE_DIR}/help"
readonly TRM_DIR_PATH="${EXEC_FILE_DIR}/trm"
readonly CUT_DIR_PATH="${EXEC_FILE_DIR}/cut"
readonly C2S_DIR_PATH="${EXEC_FILE_DIR}/c2s"
readonly MCH_DIR_PATH="${EXEC_FILE_DIR}/mch"
readonly AWK_DIR_PATH="${EXEC_FILE_DIR}/awk"
readonly REP_DIR_PATH="${EXEC_FILE_DIR}/rep"
readonly HLD_DIR_PATH="${EXEC_FILE_DIR}/hld"
readonly UP_DIR_PATH="${EXEC_FILE_DIR}/up"
readonly IF_DIR_PATH="${EXEC_FILE_DIR}/if"
readonly TRM_SUB_CMD=$(basename "${TRM_DIR_PATH}")
readonly CUT_SUB_CMD=$(basename "${CUT_DIR_PATH}")
readonly C2S_SUB_CMD=$(basename "${C2S_DIR_PATH}")
readonly MCH_SUB_CMD=$(basename "${MCH_DIR_PATH}")
readonly AWK_SUB_CMD=$(basename "${AWK_DIR_PATH}")
readonly REP_SUB_CMD=$(basename "${REP_DIR_PATH}")
readonly HLD_SUB_CMD=$(basename "${HLD_DIR_PATH}")
readonly UP_SUB_CMD=$(basename "${UP_DIR_PATH}")
readonly IF_SUB_CMD=$(basename "${IF_DIR_PATH}")

. "${HELP_DIR_PATH}/help.sh"
. "${TRM_DIR_PATH}/trm.sh"
. "${CUT_DIR_PATH}/cut.sh"
. "${C2S_DIR_PATH}/c2s.sh"
. "${MCH_DIR_PATH}/mch.sh"
. "${AWK_DIR_PATH}/awk.sh"
. "${REP_DIR_PATH}/rep.sh"
. "${HLD_DIR_PATH}/hld.sh"
. "${UP_DIR_PATH}/up.sh"
. "${IF_DIR_PATH}/if.sh"


readonly AWK_HOME_PATH="${HOME}/.${AKU_CMD_NAME}"
test -d "${AWK_HOME_PATH}" \
|| mkdir -p "${AWK_HOME_PATH}"
readonly AWK_CMD_TXT_PATH="${AWK_HOME_PATH}/cmd.txt"
readonly default_awk="awk"
AWK_PATH="${default_awk}"
if [  -f "${AWK_CMD_TXT_PATH}" ];then
	AWK_PATH=$(\
		awk '(NR==1){ print }' \
			"${AWK_CMD_TXT_PATH}"\
	)
	test -f "${AWK_PATH}" \
		|| AWK_PATH="${default_awk}"
fi
readonly DEFAULT_DELIMITTER=" "

HELP=""
case "${AKU_SUB_CMD}" in
	${TRM_SUB_CMD})
		CONTENTS=""
		DELETE_PREFIXS=""
		DELETE_SUFFIX=""
		DELETE_CONTAIN=""
		DELETE_REGEX=""
		ON_AND=""
		REGEX_LIST_CON=""
		TRIM_STR_LIST_CON=""
		PREFIX_SEPARATOR="TRIM_CCCD_SEPARATOR"
		TRIM_STR_SEPARATOR="TRIM_STR_CCCD_SEPARATOR"
		read_args_for_trm "${@}"
		display_help_for_trm
		exec_trm
		;;
	${CUT_SUB_CMD})
		CONTENTS=""
		DELIMITTER="${DEFAULT_DELIMITTER}"
		FIELD_NUM_LIST_CON=""
		ROW_NUM_LIST_CON=""
		NUM_LIST_CON_SEPARATOR="FIELD_CCCD_SEPARATOR"
		read_args_for_cut "${@}"
		display_help_for_cut
		exec_cut
		;;
	${C2S_SUB_CMD})
		CONTENTS=""
		REVERSE=""
		REPLACE_UNDER_BAR2SPACE=""
		read_args_for_c2s "${@}"
		display_help_for_c2s
		c2s_handler
		;;
	${MCH_SUB_CMD})
		CONTENTS=""
		DELIMITTER="${DEFAULT_DELIMITTER}"
		ON_AND=""
		FIELD_NUM_TO_REGEX_LIST_CON=""
		FIELD_NUM_TO_NEGATIVE_REGEX_LIST_CON=""
		NUM_LIST_CON_SEPARATOR="FIELD_CCCD_SEPARATOR"
		NUM_REGEX_SEPARATOR=":"
		read_args_for_mch "${@}"
		display_help_for_mch
		exec_mch
		;;
	${AWK_SUB_CMD})
		CONTENTS=""
		read_args_for_awk "${@}"
		display_help_for_awk
		exec_awk
		;;
	${REP_SUB_CMD})
		CONTENTS=""
		FIELD_NUM_TO_REMOVE_REGEX_CON=""
		FIELD_NUM_TO_STR_CON=""
		FIELD_NUM_TO_STR_LIST_CON=""
		DELIMITTER="${DEFAULT_DELIMITTER}"
		OUTPUT_DELIMITER=""
		TURN=""
		NUM_REGEX_SEPARATOR=":"
		read_args_for_rep "${@}"
		display_help_for_rep
		exec_rep
		;;
	${HLD_SUB_CMD})
		CONTENTS=""
		START_HOLDER_LIST_CON=""
		END_HOLDER_LIST_CON=""
		HOLDER_LAYOUT=""
		HOLDER_LIST_CON_SEPARATOR="HOLDER_CCCD_SEPARATOR"
		ON_NEGATIVE=""
		BOUND_STR=""
		read_args_for_hld "${@}"
		display_help_for_hld
		exec_hld
		;;
	${UP_SUB_CMD})
		CONTENTS=""
		POSITION=""
		FUNC_NAME="toupper"
		read_args_for_up "${@}"
		display_help_for_up
		exec_up
		;;
	${IF_SUB_CMD})
		CONTENTS=""
		ARG_SEPARATOR=""
		REGEX_CON=""
		CMD_CON=""
		DELIMITTER="${DEFAULT_DELIMITTER}"
		read_args_for_if "${@}"
		display_help_for_if
		exec_if
		;;
	*)
		display_help_for_aku
		;;
esac
		