#!/bin/bash

set -eu


LANG=C
AKU_SUB_CMD="${1:-}"
readonly AKU_CMD_NAME="$(basename $0)"
readonly AKU_LIBS_DIR_PATH="$(cd $(dirname $0) ; pwd)"
readonly EXEC_FILE_DIR="${AKU_LIBS_DIR_PATH}/aku_libs"
readonly LIBS_DIR_PATH="${EXEC_FILE_DIR}/libs"
readonly AWK_LIST_FUNCS_PATH="${LIBS_DIR_PATH}/list.awk"
readonly AWK_LINE_FUNCS_PATH="${LIBS_DIR_PATH}/line.awk"
readonly HELP_DIR_PATH="${EXEC_FILE_DIR}/help"
readonly TRM_DIR_PATH="${EXEC_FILE_DIR}/trm"
readonly CUT_DIR_PATH="${EXEC_FILE_DIR}/cut"
readonly C2S_DIR_PATH="${EXEC_FILE_DIR}/c2s"
readonly MCH_DIR_PATH="${EXEC_FILE_DIR}/mch"
readonly AWK_DIR_PATH="${EXEC_FILE_DIR}/awk"
readonly REP_DIR_PATH="${EXEC_FILE_DIR}/rep"
readonly HLD_DIR_PATH="${EXEC_FILE_DIR}/hld"
readonly UP_DIR_PATH="${EXEC_FILE_DIR}/up"
readonly IF_DIR_PATH="${EXEC_FILE_DIR}/if"
readonly TR_DIR_PATH="${EXEC_FILE_DIR}/tr"
readonly UNI_DIR_PATH="${EXEC_FILE_DIR}/uni"
readonly FLD_DIR_PATH="${EXEC_FILE_DIR}/fld"
readonly SD_DIR_PATH="${EXEC_FILE_DIR}/sd"
readonly IRO_DIR_PATH="${EXEC_FILE_DIR}/iro"
readonly TRM_SUB_CMD="${TRM_DIR_PATH##*/}"
readonly CUT_SUB_CMD="${CUT_DIR_PATH##*/}"
readonly C2S_SUB_CMD="${C2S_DIR_PATH##*/}"
readonly MCH_SUB_CMD="${MCH_DIR_PATH##*/}"
readonly AWK_SUB_CMD="${AWK_DIR_PATH##*/}"
readonly REP_SUB_CMD="${REP_DIR_PATH##*/}"
readonly HLD_SUB_CMD="${HLD_DIR_PATH##*/}"
readonly UP_SUB_CMD="${UP_DIR_PATH##*/}"
readonly IF_SUB_CMD="${IF_DIR_PATH##*/}"
readonly TR_SUB_CMD="${TR_DIR_PATH##*/}"
readonly UNI_SUB_CMD="${UNI_DIR_PATH##*/}"
readonly FLD_SUB_CMD="${FLD_DIR_PATH##*/}"
readonly SD_SUB_CMD="${SD_DIR_PATH##*/}"
readonly IRO_SUB_CMD="${IRO_DIR_PATH##*/}"

readonly AWK_HOME_PATH="${HOME}/.${AKU_CMD_NAME}"
test -d "${AWK_HOME_PATH}" \
|| mkdir -p "${AWK_HOME_PATH}"
readonly AWK_CMD_TXT_PATH="${AWK_HOME_PATH}/cmd.txt"
readonly default_awk="awk"
AWK_PATH="${default_awk}"
if [  -f "${AWK_CMD_TXT_PATH}" ];then
	AWK_PATH=$(\
		awk '(NR==1){ print }' \
			"${AWK_CMD_TXT_PATH}"\
	)
	test -f "${AWK_PATH}" \
		|| AWK_PATH="${default_awk}"
fi
readonly DEFAULT_DELIMITTER=" "

HELP=""
case "${AKU_SUB_CMD}" in
	${TRM_SUB_CMD})
		. "${TRM_DIR_PATH}/trm.sh"
		CONTENTS=""
		DELETE_PREFIXS=""
		DELETE_SUFFIX=""
		DELETE_CONTAIN=""
		DELETE_REGEX=""
		ON_AND=""
		REGEX_LIST_CON=""
		TRIM_STR_LIST_CON=""
		PREFIX_SEPARATOR="TRIM_CCCD_SEPARATOR"
		TRIM_STR_SEPARATOR="TRIM_STR_CCCD_SEPARATOR"
		read_args_for_trm "${@}"
		display_help_for_trm
		exec_trm
		;;
	${CUT_SUB_CMD})
		. "${CUT_DIR_PATH}/cut.sh"
		CONTENTS=""
		DELIMITTER="${DEFAULT_DELIMITTER}"
		FIELD_NUM_LIST_CON=""
		ROW_NUM_LIST_CON=""
		NUM_LIST_CON_SEPARATOR="FIELD_CCCD_SEPARATOR"
		ON_NEGATIVE=""
		read_args_for_cut "${@}"
		display_help_for_cut
		exec_cut
		;;
	${C2S_SUB_CMD})
		. "${C2S_DIR_PATH}/c2s.sh"
		CONTENTS=""
		REVERSE=""
		REPLACE_UNDER_BAR2SPACE=""
		read_args_for_c2s "${@}"
		display_help_for_c2s
		c2s_handler
		;;
	${MCH_SUB_CMD})
		. "${MCH_DIR_PATH}/mch.sh"
		CONTENTS=""
		DELIMITTER="${DEFAULT_DELIMITTER}"
		ON_AND=""
		FIELD_NUM_TO_REGEX_LIST_CON=""
		FIELD_NUM_TO_NEGATIVE_REGEX_LIST_CON=""
		NUM_LIST_CON_SEPARATOR="FIELD_CCCD_SEPARATOR"
		NUM_REGEX_SEPARATOR=":"
		read_args_for_mch "${@}"
		display_help_for_mch
		exec_mch
		;;
	${AWK_SUB_CMD})
		. "${AWK_DIR_PATH}/awk.sh"
		CONTENTS=""
		read_args_for_awk "${@}"
		display_help_for_awk
		exec_awk
		;;
	${REP_SUB_CMD})
		. "${REP_DIR_PATH}/rep.sh"
		CONTENTS=""
		FIELD_NUM_TO_REMOVE_REGEX_CON=""
		FIELD_NUM_TO_STR_CON=""
		FIELD_NUM_TO_STR_LIST_CON=""
		DELIMITTER="${DEFAULT_DELIMITTER}"
		OUTPUT_DELIMITER=""
		ROW_NUM_LIST_CON=""
		NUM_LIST_CON_SEPARATOR="FIELD_CCCD_SEPARATOR"
		TURN=""
		NUM_REGEX_SEPARATOR=":"
		read_args_for_rep "${@}"
		display_help_for_rep
		exec_rep
		;;
	${HLD_SUB_CMD})
		. "${HLD_DIR_PATH}/hld.sh"
		CONTENTS=""
		START_HOLDER_LIST_CON=""
		END_HOLDER_LIST_CON=""
		HOLDER_LAYOUT=""
		HOLDER_LIST_CON_SEPARATOR="HOLDER_CCCD_SEPARATOR"
		ON_NEGATIVE=""
		BOUND_STR=""
		read_args_for_hld "${@}"
		display_help_for_hld
		exec_hld
		;;
	${UP_SUB_CMD})
		. "${UP_DIR_PATH}/up.sh"
		CONTENTS=""
		POSITION=""
		FUNC_NAME="toupper"
		read_args_for_up "${@}"
		display_help_for_up
		exec_up
		;;
	${IF_SUB_CMD})
		. "${IF_DIR_PATH}/if.sh"
		CONTENTS=""
		ARG_SEPARATOR=""
		REGEX_CON=""
		CMD_CON=""
		DELIMITTER="${DEFAULT_DELIMITTER}"
		read_args_for_if "${@}"
		display_help_for_if
		exec_if
		;;
	${TR_SUB_CMD})
		. "${TR_DIR_PATH}/tr.sh"
		CONTENTS=""
		REGEX_CON="\n"
		REPLACE_STR=""
		NUM_LIST_CON_SEPARATOR="NUM_CCCD_SEPARATOR"
		TURN_LIST_CON="g"
		read_args_for_tr "${@}"
		display_help_for_tr
		exec_tr
		;;
	${UNI_SUB_CMD})
		. "${UNI_DIR_PATH}/uni.sh"
		CONTENTS=""
		BOUND_STR="\n"
		VAL_LIST_CON_SEPARATOR="G57VES_T5Y753VHi_DGV365RJY7i_SEPARATOR_V86YR"
		read_args_for_uni "${@}"
		display_help_for_uni
		exec_uni
		;;
	${FLD_SUB_CMD})
		. "${FLD_DIR_PATH}/fld.sh"
		CONTENTS=""
		HEADER_ROW_NUM="1"
		FOID_COL_CYCLE=5
		INSERT_HEADER_CYCLE=5
		DELIMITTER=" "
		BOUND_STR=">Index-@{NR}\n"
		ON_PREFIX=""
		ON_GREEM=""
		DEFAULT_PREFIX=">"
		read_args_for_fld "${@}"
		display_help_for_fld
		exec_fld
		;;
	${SD_SUB_CMD})
		. "${SD_DIR_PATH}/sd.sh"
		CONTENTS=""
		TURN="g"
		ROW_NUM_LIST_CON=""
		NUM_LIST_CON_SEPARATOR="FIELD_CCCD_SEPARATOR"
		REGEX_CON=""
		REPLACE_STR=""
		read_args_for_sd "${@}"
		display_help_for_sd
		exec_sd
		;;
	${IRO_SUB_CMD})
		. "${IRO_DIR_PATH}/iro.sh"
		CONTENTS=""
		TURN="g"
		ROW_NUM_LIST_CON=""
		FIELD_NUM_LIST_CON=""
		NUM_LIST_CON_SEPARATOR="FIELD_CCCD_SEPARATOR"
		DELIMITTER="${DEFAULT_DELIMITTER}"
		PROPERTY="color:green,bold"
		PROPERTY_SEPARATOR=","
		REGEX_CON='(.*)'
		REPLACE_STR=""
		ON_NEGATIVE=""
		read_args_for_iro "${@}"
		display_help_for_iro
		exec_iro
		;;
	*)
		. "${HELP_DIR_PATH}/help.sh"
		display_help_for_aku
		;;
esac
		